name: berks_todo_app
description: "Kendi Keyfime Göre Todo Uygulamam"
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.3.2
  path: ^1.9.0
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  timezone: ^0.9.2
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
flutter:
  uses-material-design: true